name: "PRMate Review"
description: "PRMate's automated review for a Pull Request"
author: "Rooam Lee"
branding:
  color: "purple"
  icon: "check"

inputs:
  pr-number:
    description: >
      The number of the Pull Request to review.
      This is required to specify which PR PRMate should analyze.
    required: true
  repository:
    description: >
      The full name of the repository containing the Pull Request,
      including the owner. For example, 'owner/repository-name'.
    required: true
    default: ${{ github.repository }}
  token:
    description: >
      GitHub token for API authentication.
      Needs write access to issues and pull requests
      in order to post review comments.
    required: true
    default: ${{ github.token }}
  openai-api-key:
    description: >
      Optional OpenAI API key (required if not using Ollama).
    required: false
    default: ""
  ollama-host:
    description: >
      Optional Ollama host URL (used if running a local Ollama server).
    required: false
    default: "http://127.0.0.1:11434"
  review-language:
    description: >
      Language of the code review output ('Korean' or 'English').
    required: false
    default: "Korean"
  review-strict:
    description: >
      Whether to use strict review formatting ("True" to enable strict mode).
    required: false
    default: "False"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: leewr9/prmate
        path: prmate-dist
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        
    - name: Install uv and Sync dependencies
      shell: bash
      run: |
        cd prmate-dist
        python -m pip install --upgrade pip
        pip install uv
        uv sync

    - name: Run PRMate review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        OLLAMA_HOST: ${{ inputs.ollama-host }}
        REVIEW_LANG: ${{ inputs.review-language }}
        REVIEW_STRICT: ${{ inputs.review-strict }}
      run: |
        cd prmate-dist
        uv run python -m app.main ${{ inputs.pr-number }} ${{ inputs.repository }}
