name: "PRMate Review"
description: "PRMate's automated review for a Pull Request"
author: "Rooam Lee"
branding:
  color: 'purple'
  icon: 'check'

inputs:
  pr_number:
    description: >
      The number of the Pull Request to review.
      This is required to specify which PR PRMate should analyze.
    required: true
  repo_name:
    description: >
      The full name of the repository containing the Pull Request,
      including the owner. For example, 'owner/repository-name'.
    required: true
    default: ${{ github.repository }}


runs:
  using: "composite"
  steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        
    - name: Install uv and Sync dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync

    - name: Run PRMate review
      run: uv run python -m app.main ${{ inputs.pr_number }} ${{ inputs.repo_name }}
