name: PRMate Review (OpenAI)

on:
  pull_request:
    types: [opened, reopened]
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-release:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

        
    - name: Clone PRMate
      run: |
        git clone https://github.com/leewr9/prmate.git
        cd prmate
        
    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv
    - name: Sync dependencies with uv
      run: |
        uv sync


    - name: Run PRMate code review
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required GitHub token for authenticating API calls and posting PR comments
        OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}  # Optional OpenAI API key (required if not using Ollama)
        REVIEW_LANG: "Korean"  # Language of the code review output ("Korean" or "English")
        REVIEW_STRICT: False  # Whether to use strict review formatting ("True" to enable strict mode)
      run: |
        uv run python -m app.main ${{ github.event.pull_request.number }} ${{ github.repository }}