name: PRMate Review

on:
  pull_request:
    types: [opened, reopened]
    branches: [ "master" ]

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required GitHub token for authenticating API calls and posting PR comments
  OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}  # Optional OpenAI API key (required if not using Ollama)
  OLLAMA_HOST: ${{ secrets.OLLAMA_HOST }}  # Optional Ollama host URL (used if running a local Ollama server)
  REVIEW_LANG: "Korean"  # Language of the code review output ("Korean" or "English")
  REVIEW_STRICT: False  # Whether to use strict review formatting ("True" to enable strict mode)

jobs:
  
  job-with-openai:
    if: env.OPEN_API_KEY != ''
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        
    - name: Clone PRMate
      run: |
        git clone https://github.com/leewr9/prmate.git
        cd prmate
        
    - name: Install uv and Sync dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync

    - name: Run PRMate code review
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}
        REVIEW_LANG: ${{ env.REVIEW_LANG }}
        REVIEW_STRICT: ${{ env.REVIEW_STRICT }}
      run: |
        uv run python -m app.main ${{ github.event.pull_request.number }} ${{ github.repository }}


  job-with-ollama:
    if: env.OPEN_API_KEY == ''
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        
    - name: Clone PRMate
      run: |
        git clone https://github.com/leewr9/prmate.git
        cd prmate
        
    - name: Install uv and Sync dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync

    - name: Run PRMate code review
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OLLAMA_HOST: ${{ secrets.OLLAMA_HOST }}
        REVIEW_LANG: ${{ env.REVIEW_LANG }}
        REVIEW_STRICT: ${{ env.REVIEW_STRICT }}
      run: |
        uv run python -m app.main ${{ github.event.pull_request.number }} ${{ github.repository }}

